NAME: pretraining_pointcloud

DATASET:
  root: /data2/zhangyc/zebra_fish_refine/mesh[F]-merge
  n_point: 3072

TRAIN:
  if_cuda: true
  cache_path: ./cache
  save_path: ./save
  batch_size: 16
  num_workers: 4
  resume: false
  model_name: pretrain_test
  model_id: 0
  total_iters: 100000
  display_freq: 50
  save_freq: 1000
  base_lr: 0.001
  end_lr: 0.00001
  warmup_iters: 1000
  decay_iters: 80000
  power: 0.9
  weight_decay: 1e-4

MODEL:
  pre_train: false
  pretrain_path: ""
